[server]
headless = true
address = "0.0.0.0"
port = 5000
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = true
maxMessageSize = 200
maxUploadSize = 200

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[global]
developmentMode = false
showWarningOnDirectExecution = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
