[server]
headless = true
address = "0.0.0.0"
port = 8501
enableXsrfProtection = false
enableCORS = true
baseUrlPath = ""

[browser]
serverAddress = "outfitwiz.site"
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
