[server]
headless = true
address = "0.0.0.0"
port = 8501
enableXsrfProtection = false
enableCORS = false
baseUrlPath = ""
enableWebsocketCompression = true
runOnSave = true
enableStaticServing = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverPort = 8501
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[client]
showErrorDetails = true
toolbarMode = "minimal"
showSidebarNavigation = true

[runner]
fastReruns = true
magicEnabled = true
